// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfyjoWTztHRJm2xr3uDCboCXEgr0-WNcI',
    appId: '1:330659293333:web:fbce262c506009c04f939c',
    messagingSenderId: '330659293333',
    projectId: 'jobpilot-730b5',
    authDomain: 'jobpilot-730b5.firebaseapp.com',
    storageBucket: 'jobpilot-730b5.firebasestorage.app',
    measurementId: 'G-PBNC6GX0LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4XCp_DBq7sTBg1pWhsLCMegDcRvI3Hfk',
    appId: '1:330659293333:android:de3d181d9ac9eebb4f939c',
    messagingSenderId: '330659293333',
    projectId: 'jobpilot-730b5',
    storageBucket: 'jobpilot-730b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4B6Qkufo9KYluoP8fP8k0ubOohODqhcs',
    appId: '1:330659293333:ios:e4421c61017a16fd4f939c',
    messagingSenderId: '330659293333',
    projectId: 'jobpilot-730b5',
    storageBucket: 'jobpilot-730b5.firebasestorage.app',
    iosBundleId: 'com.example.jobpilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4B6Qkufo9KYluoP8fP8k0ubOohODqhcs',
    appId: '1:330659293333:ios:e4421c61017a16fd4f939c',
    messagingSenderId: '330659293333',
    projectId: 'jobpilot-730b5',
    storageBucket: 'jobpilot-730b5.firebasestorage.app',
    iosBundleId: 'com.example.jobpilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfyjoWTztHRJm2xr3uDCboCXEgr0-WNcI',
    appId: '1:330659293333:web:7a14088bfc1ce56d4f939c',
    messagingSenderId: '330659293333',
    projectId: 'jobpilot-730b5',
    authDomain: 'jobpilot-730b5.firebaseapp.com',
    storageBucket: 'jobpilot-730b5.firebasestorage.app',
    measurementId: 'G-V2GT9K1GLY',
  );
}
